/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  LabTestResult as PrismaLabTestResult,
  TestType as PrismaTestType,
  LabTechnician as PrismaLabTechnician,
} from "@prisma/client";

export class LabTestResultServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.LabTestResultCountArgs, "select">
  ): Promise<number> {
    return this.prisma.labTestResult.count(args);
  }

  async labTestResults(
    args: Prisma.LabTestResultFindManyArgs
  ): Promise<PrismaLabTestResult[]> {
    return this.prisma.labTestResult.findMany(args);
  }
  async labTestResult(
    args: Prisma.LabTestResultFindUniqueArgs
  ): Promise<PrismaLabTestResult | null> {
    return this.prisma.labTestResult.findUnique(args);
  }
  async createLabTestResult(
    args: Prisma.LabTestResultCreateArgs
  ): Promise<PrismaLabTestResult> {
    return this.prisma.labTestResult.create(args);
  }
  async updateLabTestResult(
    args: Prisma.LabTestResultUpdateArgs
  ): Promise<PrismaLabTestResult> {
    return this.prisma.labTestResult.update(args);
  }
  async deleteLabTestResult(
    args: Prisma.LabTestResultDeleteArgs
  ): Promise<PrismaLabTestResult> {
    return this.prisma.labTestResult.delete(args);
  }

  async getTestType(parentId: string): Promise<PrismaTestType | null> {
    return this.prisma.labTestResult
      .findUnique({
        where: { id: parentId },
      })
      .testType();
  }

  async getLabTechnician(
    parentId: string
  ): Promise<PrismaLabTechnician | null> {
    return this.prisma.labTestResult
      .findUnique({
        where: { id: parentId },
      })
      .labTechnician();
  }
}
