/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";

import {
  IsString,
  MaxLength,
  IsOptional,
  IsInt,
  Min,
  Max,
  IsEnum,
  IsDate,
  ValidateNested,
} from "class-validator";

import { EnumDocumentWorkflowStatus } from "./EnumDocumentWorkflowStatus";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { Type } from "class-transformer";
import { WorkflowUpdateManyWithoutDocumentsInput } from "./WorkflowUpdateManyWithoutDocumentsInput";
import { VersionUpdateManyWithoutDocumentsInput } from "./VersionUpdateManyWithoutDocumentsInput";

@InputType()
class DocumentUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  content?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  documentVersion?: number | null;

  @ApiProperty({
    required: false,
    enum: EnumDocumentWorkflowStatus,
  })
  @IsEnum(EnumDocumentWorkflowStatus)
  @IsOptional()
  @Field(() => EnumDocumentWorkflowStatus, {
    nullable: true,
  })
  workflowStatus?: "Option1" | null;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  metadata?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  checkedOutBy?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  checkedOutAt?: Date | null;

  @ApiProperty({
    required: false,
    type: () => WorkflowUpdateManyWithoutDocumentsInput,
  })
  @ValidateNested()
  @Type(() => WorkflowUpdateManyWithoutDocumentsInput)
  @IsOptional()
  @Field(() => WorkflowUpdateManyWithoutDocumentsInput, {
    nullable: true,
  })
  workflows?: WorkflowUpdateManyWithoutDocumentsInput;

  @ApiProperty({
    required: false,
    type: () => VersionUpdateManyWithoutDocumentsInput,
  })
  @ValidateNested()
  @Type(() => VersionUpdateManyWithoutDocumentsInput)
  @IsOptional()
  @Field(() => VersionUpdateManyWithoutDocumentsInput, {
    nullable: true,
  })
  versions?: VersionUpdateManyWithoutDocumentsInput;
}

export { DocumentUpdateInput as DocumentUpdateInput };
