/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  IsDate,
  ValidateNested,
} from "class-validator";
import { Type } from "class-transformer";
import { LeaveRequestUpdateManyWithoutEmployeesInput } from "./LeaveRequestUpdateManyWithoutEmployeesInput";
import { PayrollRecordUpdateManyWithoutEmployeesInput } from "./PayrollRecordUpdateManyWithoutEmployeesInput";

@InputType()
class EmployeeUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  position?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  startDate?: Date | null;

  @ApiProperty({
    required: false,
    type: () => LeaveRequestUpdateManyWithoutEmployeesInput,
  })
  @ValidateNested()
  @Type(() => LeaveRequestUpdateManyWithoutEmployeesInput)
  @IsOptional()
  @Field(() => LeaveRequestUpdateManyWithoutEmployeesInput, {
    nullable: true,
  })
  leaveRequests?: LeaveRequestUpdateManyWithoutEmployeesInput;

  @ApiProperty({
    required: false,
    type: () => PayrollRecordUpdateManyWithoutEmployeesInput,
  })
  @ValidateNested()
  @Type(() => PayrollRecordUpdateManyWithoutEmployeesInput)
  @IsOptional()
  @Field(() => PayrollRecordUpdateManyWithoutEmployeesInput, {
    nullable: true,
  })
  payrollRecords?: PayrollRecordUpdateManyWithoutEmployeesInput;
}

export { EmployeeUpdateInput as EmployeeUpdateInput };
