/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { TestTypeService } from "../testType.service";
import { TestTypeCreateInput } from "./TestTypeCreateInput";
import { TestType } from "./TestType";
import { TestTypeFindManyArgs } from "./TestTypeFindManyArgs";
import { TestTypeWhereUniqueInput } from "./TestTypeWhereUniqueInput";
import { TestTypeUpdateInput } from "./TestTypeUpdateInput";
import { LabTestResultFindManyArgs } from "../../labTestResult/base/LabTestResultFindManyArgs";
import { LabTestResult } from "../../labTestResult/base/LabTestResult";
import { LabTestResultWhereUniqueInput } from "../../labTestResult/base/LabTestResultWhereUniqueInput";

export class TestTypeControllerBase {
  constructor(protected readonly service: TestTypeService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: TestType })
  async createTestType(
    @common.Body() data: TestTypeCreateInput
  ): Promise<TestType> {
    return await this.service.createTestType({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        testName: true,
        description: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [TestType] })
  @ApiNestedQuery(TestTypeFindManyArgs)
  async testTypes(@common.Req() request: Request): Promise<TestType[]> {
    const args = plainToClass(TestTypeFindManyArgs, request.query);
    return this.service.testTypes({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        testName: true,
        description: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: TestType })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async testType(
    @common.Param() params: TestTypeWhereUniqueInput
  ): Promise<TestType | null> {
    const result = await this.service.testType({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        testName: true,
        description: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: TestType })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateTestType(
    @common.Param() params: TestTypeWhereUniqueInput,
    @common.Body() data: TestTypeUpdateInput
  ): Promise<TestType | null> {
    try {
      return await this.service.updateTestType({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          testName: true,
          description: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: TestType })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteTestType(
    @common.Param() params: TestTypeWhereUniqueInput
  ): Promise<TestType | null> {
    try {
      return await this.service.deleteTestType({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          testName: true,
          description: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/labTestResults")
  @ApiNestedQuery(LabTestResultFindManyArgs)
  async findLabTestResults(
    @common.Req() request: Request,
    @common.Param() params: TestTypeWhereUniqueInput
  ): Promise<LabTestResult[]> {
    const query = plainToClass(LabTestResultFindManyArgs, request.query);
    const results = await this.service.findLabTestResults(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        resultValue: true,
        testDate: true,

        testType: {
          select: {
            id: true,
          },
        },

        labTechnician: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/labTestResults")
  async connectLabTestResults(
    @common.Param() params: TestTypeWhereUniqueInput,
    @common.Body() body: LabTestResultWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      labTestResults: {
        connect: body,
      },
    };
    await this.service.updateTestType({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/labTestResults")
  async updateLabTestResults(
    @common.Param() params: TestTypeWhereUniqueInput,
    @common.Body() body: LabTestResultWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      labTestResults: {
        set: body,
      },
    };
    await this.service.updateTestType({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/labTestResults")
  async disconnectLabTestResults(
    @common.Param() params: TestTypeWhereUniqueInput,
    @common.Body() body: LabTestResultWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      labTestResults: {
        disconnect: body,
      },
    };
    await this.service.updateTestType({
      where: params,
      data,
      select: { id: true },
    });
  }
}
